### PR TITLE
pin pip package versions

### PR DESCRIPTION
**Pull request by kwypchlo**
- pin specific versions of packages instead of using latest
- also according to [ansible pip docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) we don't need to define loop, we can just define a number of packages we want installed

### CODE REVIEW

**Comment by kwypchlo** [comment]
> > also according to [ansible pip docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) we don't need to define loop, we can just define a number of packages we want installed
> 
> the loop was to refactor the packages since they were all using latest. so yes, if you are defining different images for all the packages it doesn't make sense to use the loop.

Can you clarify? We could have used "name" list even without pinning versions, still not sure what the loop was for.

**Comment by MSevey** [comment]
have we tested this on a dev server?

**Comment by MSevey** [comment]
> > > also according to [ansible pip docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) we don't need to define loop, we can just define a number of packages we want installed
> > 
> > 
> > the loop was to refactor the packages since they were all using latest. so yes, if you are defining different images for all the packages it doesn't make sense to use the loop.
> 
> Can you clarify? We could have used "name" list even without pinning versions, still not sure what the loop was for.

followed up on discord

**Comment by kwypchlo** [comment]
> have we tested this on a dev server?

I tested it on as-hk-1 when deploying latest tag and it worked just fine

**Review by MSevey — APPROVED** [review]

**Pull request merged**
